### ISSUE TITLE
You need to remove your HutongGames.PlayMaker.Actions using references from the scripts

### ISSUE THREAD

**Issue by devotionsolutions** [mdotstrange/CustomBehaviorDesignerTasks#1]
You need to remove your HutongGames.PlayMaker.Actions using references from the scripts

Thanks for sharing!

**Comment by mdotstrange** [comment]
Thanks for the heads up! I'll go through them now and remove the refs-thx

**Comment by mdotstrange** [comment]
I removed the hutong games namespace ref from several of the tasks- removed the package download as I need to update/re-export it-
